site_name: Oniro Project
site_url: https://docs.oniroproject.org/
theme:
 name: material
 features:
   - content.code.copy
   - content.code.select
   - navigation.footer
 font: 
  text: Plus Jakarta Sans
  code: Plus Jakarta Sans # Change font in code
 logo: assets/oniro_white.png
 favicon: assets/favicon.ico
 palette: 
  # Light mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
    primary: custom
    accent: custom
   # Dark mode
  - scheme: slate
    toggle:
     icon: material/weather-sunny
     name: Switch to light mode
    primary: custom
    accent: custom

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
nav:
  - Home: index.md
  - Eclipse Oniro Project:
      - OpenHarmony Downstream / Upstream Relationship: eclipse-oniro-project/openharmony-relationship.md
      - OpenHarmony Mirror: eclipse-oniro-project/openharmony-mirror.md
      - Oniro Architecture: eclipse-oniro-project/oniro-architecture.md
  - Application Development: 
      - Development Overview: application-development/index.md
      - Environment Setup Guide: 
        - Overview: application-development/environment-setup-config/index.md
        - System Requirement: application-development/environment-setup-config/system-requirement.md
        - IDE Installation: application-development/environment-setup-config/ide-installation.md
        - Environment Configuration: application-development/environment-setup-config/env-config.md
        - Full SDK & Public SDK: application-development/environment-setup-config/full-public-sdk.md
        - Developer Account: application-development/environment-setup-config/developer-account.md
        - Introduction to OHPM: application-development/environment-setup-config/ohpm.md
        - Common Issues and Solutions: application-development/environment-setup-config/common-issue.md
        - Oniro IDE: application-development/environment-setup-config/oniro-ide.md
      - Create Your First Eclipse Oniro Application:
        - Mobile: 
          - Overview: application-development/create-first-eclipse-oniro-app/mobile/index.md
          - Create an Eclipse Oniro app using OpenHarmony Template: application-development/create-first-eclipse-oniro-app/mobile/create-template.md
          - Find Project Files: application-development/create-first-eclipse-oniro-app/mobile/find-project-files.md
          - Usage of Previewer: application-development/create-first-eclipse-oniro-app/mobile/use-previewer.md
          - Build the First Page: application-development/create-first-eclipse-oniro-app/mobile/build-first-page.md
          - Build the Second Page: application-development/create-first-eclipse-oniro-app/mobile/build-second-page.md
          - Implementing Page Redirection: application-development/create-first-eclipse-oniro-app/mobile/page-redirect.md
          - Running the Application on a Real Device: application-development/create-first-eclipse-oniro-app/mobile/run-real-device.md
        - Wearable: 
          - Overview: application-development/create-first-eclipse-oniro-app/wearable/index.md
          - Create an Eclipse Oniro app using OpenHarmony Template: application-development/create-first-eclipse-oniro-app/wearable/create-template.md
          - Find Project Files: application-development/create-first-eclipse-oniro-app/wearable/find-project-files.md
          - Usage of Previewer: application-development/create-first-eclipse-oniro-app/wearable/use-previewer.md
          - Build the First Page: application-development/create-first-eclipse-oniro-app/wearable/build-first-page.md
          - Build the Second Page: application-development/create-first-eclipse-oniro-app/wearable/build-second-page.md
          - Implementing Page Redirection: application-development/create-first-eclipse-oniro-app/wearable/page-redirect.md
          - Running the Application on a Real Device: application-development/create-first-eclipse-oniro-app/wearable/run-real-device.md
        - Module Development:
          - Overview: application-development/create-first-eclipse-oniro-app/module-development/index.md
          - Create a Module Project: application-development/create-first-eclipse-oniro-app/module-development/create-module-project.md
          - Add HSP Dependency: application-development/create-first-eclipse-oniro-app/module-development/add-hsp-dependency.md
          - How to use shared packages: application-development/create-first-eclipse-oniro-app/module-development/how-to-use-shared-packages.md
          - Best Practice: application-development/create-first-eclipse-oniro-app/module-development/practice-example.md
      - Basic Concepts: 
        - Overview: application-development/basic-concepts/index.md
        - Application Package Structure in Stage Model: application-development/basic-concepts/app-pack-structure.md
        - Introduction to ArkTS: application-development/basic-concepts/introduction-to-arkts.md
        - ArkTS Language Reference: application-development/basic-concepts/arkts-language-reference.md
        - ArkTS-Based declarative UI Development: 
          - Overview: application-development/basic-concepts/ui-development/index.md
          - Component: application-development/basic-concepts/ui-development/component.md
          - Layout: application-development/basic-concepts/ui-development/layout.md
        - UIAbility: 
          - Overview: application-development/basic-concepts/uiability/index.md
          - UIAbility Component Lifecycle: application-development/basic-concepts/uiability/uiability-lifecycle.md
          - UIAbility Launch Type: application-development/basic-concepts/uiability/uiability-launch-type.md
        - State Management: 
          - Overview: application-development/basic-concepts/state-management/index.md
          - State Decorator: application-development/basic-concepts/state-management/state-decorator.md
          - Prop Decorator: application-development/basic-concepts/state-management/prop-decorator.md
          - Link Decorator: application-development/basic-concepts/state-management/link-decorator.md
          - Provide and Consume Decorator: application-development/basic-concepts/state-management/provide-consume-decorator.md
          - Observed and ObjectLink Decorator: application-development/basic-concepts/state-management/observed-objectlink-decorator.md
          - LocalStorage: application-development/basic-concepts/state-management/localstorage.md
          - AppStorage: application-development/basic-concepts/state-management/appstorage.md
          - PersistentStorage: application-development/basic-concepts/state-management/persistentstorage.md
          - Watch Decorator: application-development/basic-concepts/state-management/watch-decorator.md
          - $$ Syntax: application-development/basic-concepts/state-management/operator.md 
      - Resource Categories and Access: 
        - Overview: application-development/resource-categories-and-access/index.md
        - Resource Categories:
            - Overview: application-development/resource-categories-and-access/resource-categories/index.md
            - Resource Directories: application-development/resource-categories-and-access/resource-categories/resource-directories.md
            - Resource Group Directories: application-development/resource-categories-and-access/resource-categories/resource-group-directories.md
        - Resource Access: application-development/resource-categories-and-access/resource-access/index.md
      - Code Labs: 
        - Mobile:
          - AI: application-development/codeLabs/mobile/ai.md
          - Communication: application-development/codeLabs/mobile/communication.md
          - Distributed Ability: application-development/codeLabs/mobile/distributed-ability.md
          - Education: application-development/codeLabs/mobile/education.md
          - Entertainment: application-development/codeLabs/mobile/entertainment.md
          - Utility: application-development/codeLabs/mobile/utility.md
          - Health: application-development/codeLabs/mobile/health.md
          - Information: application-development/codeLabs/mobile/information.md
          - Game: application-development/codeLabs/mobile/game.md
          - Video: application-development/codeLabs/mobile/video.md
          - Weather: application-development/codeLabs/mobile/weather.md 
        - Wearable:
          - AI: application-development/codeLabs/wearable/ai.md
          - Gesture: application-development/codeLabs/wearable/gesture.md
          - Health: application-development/codeLabs/wearable/health.md
        - Cross Platform Apps:
          - React Native Example:
            - Overview: application-development/codeLabs/cross-platform/rn-example/index.md
            - Prerequisites: application-development/codeLabs/cross-platform/rn-example/prerequisites.md
            - Development environment configuration: application-development/codeLabs/cross-platform/rn-example/development-environment-configuration.md
            - Preparation of the React Native application code: application-development/codeLabs/cross-platform/rn-example/react-native-application-code.md
            - Preparation of the OpenHarmony application code: application-development/codeLabs/cross-platform/rn-example/open-harmony-application-code.md
            - Compilation of the app: application-development/codeLabs/cross-platform/rn-example/compilation.md
            - Troubleshooting: application-development/codeLabs/cross-platform/rn-example/troubleshooting.md
        - Common Questions: application-development/codeLabs/common-problems.md 
  - Device Development: 
      - Development Overview: device-development/index.md
      - Building Oniro: device-development/building-oniro.md
      - Developer Boards: 
          - Overview: device-development/developer-boards/index.md
          - HiHope HH-SCDAYU200: device-development/developer-boards/hihope-hh-scdayu200.md
          - Raspberry Pi 4 Model B: device-development/developer-boards/raspberry-pi-4model-b.md
          - Oniro Emulator: device-development/developer-boards/emulator.md
  - Contributing:
      - Overview: contributing/index.md
      - Quick Start Guide for New Developer: contributing/quick-start-guide-for-new-developers.md
      - Eclipse Contributor Agreement: contributing/eclipse-contributor-agreement.md
      - DCO-signoff: contributing/dco-signoff.md
      - GitHub Contributions: contributing/github-contributions.md
      - Bug Handling Process: contributing/bug-handling-process.md
      - REUSE Compliance: contributing/reuse-compliance.md
      - Contributing to Projects not Maintained by Team: contributing/contributing-to-projects-not-maintained-by-team.md
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/message
      link: https://chat.eclipse.org/#/room/#oniro:matrix.eclipse.org
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@OniroProject
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/oniro-project/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Oniro_Project
